version: '3.9'
name: Project Docker

services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/conf:/etc/nginx/conf.d
    configs:
      - source: nginx_default_conf
        target: /etc/nginx/conf.d/default.conf
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    container_name: mysql_server
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sampledb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql_data:/var/lib/mysql
    configs:
      - source: mysql_config
        target: /etc/mysql/conf.d/my.cnf
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "5050:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    configs:
      - source: phpmyadmin_config
        target: /etc/phpmyadmin/config.inc.php
    depends_on:
      - mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local

configs:
  nginx_default_conf:
    file: ./nginx/conf/default.conf

  phpmyadmin_config:
    file: ./phpmyadmin/conf/config.inc.php
    
  mysql_config:
    file: ./mysql/conf/my.cnf